# Backend ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: todo-lab
  labels:
    app: todo-backend
    env: dev
data:
  MONGO_CONN_STR: "mongodb://mongodb-svc:27017/todo?directConnection=true"
  USE_DB_AUTH: "true"
  PORT: "8080"
