# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: todo-lab
  labels:
    app: todo-frontend
    env: dev
spec:
  type: ClusterIP
  selector:
    app: todo-frontend
  ports:
  - port: 80
    targetPort: frontend-port
    protocol: TCP
